language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.1

env:
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION=4.2.6

install:
  - gem update --system
  - gem install bundler
  - bundle --version
  - bundle install --jobs=3 --retry=3
